### ISSUE TITLE
Need documentation on how to query metrics in NRQL

### ISSUE THREAD

**Issue by wfeick** [newrelic/micrometer-registry-newrelic#101]
I'm having a hard time figuring out how to query my metrics after upgrading from 0.2.3 to 0.5.0. Some documented examples would be really helpful.

Let's say I have the following.
```
DistributionSummary.builder("foo").register(registry);
```
What NRQL would I use to query that data? I used to be able to do things like the following.
```
FROM Metric SELECT rate(sum(foo.count), 1 second) SINCE 1 HOUR AGO
FROM Metric SELECT max(foo.max) AS 'max' SINCE 1 HOUR AGO
FROM Metric SELECT sum(foo.total)/sum(foo.count) AS 'avg' SINCE 1 HOUR AGO
```
I gather you've switched from metrics to dimensional metrics, but googling around didn't point me in the right direction.

We're also using Counters and Gauges, so any examples for those would be appreciated as well.

**Comment by gfuller1** [comment]
Hey @wfeick , apologies for the delayed response. With dimensional metrics you'll want to use brackets instead of periods to indicate the specific fields of the metric type. So for you examples above I believe the following will return what you want.

```
FROM Metric SELECT rate(sum(foo[count]), 1 second) SINCE 1 HOUR AGO
FROM Metric SELECT max(foo[max]) AS 'max' SINCE 1 HOUR AGO
FROM Metric SELECT sum(foo[total])/sum(foo[count]) AS 'avg' SINCE 1 HOUR AGO
```

I looked around for good documentation on this and also couldn't find anything good so I'll pass that along to the appropriate team.

Let me know if this gets you the answers you want and I'll go ahead and close the issue if there isn't anything else you need.
