### ISSUE TITLE
NaN produces lots of info logs

### ISSUE THREAD

**Issue by lightbody** [newrelic/micrometer-registry-newrelic#103]
We're using Micronaut + Micrometer + Kafka, which happens to produce some metric values with NaN. Unfortunately, it appears that this integration doesn't like NaN and spews out an endless set of info logs like so:

```
11:37:26.083 [pool-1-thread-1] INFO  c.n.t.m.j.MetricBatchJsonTelemetryBlockWriter - Dropped 18 metrics from batch due to invalid metric contents (you should fix this) 
11:37:31.084 [pool-1-thread-1] INFO  c.n.t.m.j.MetricBatchJsonTelemetryBlockWriter - Dropped 18 metrics from batch due to invalid metric contents (you should fix this) 
11:37:36.085 [pool-1-thread-1] INFO  c.n.t.m.j.MetricBatchJsonTelemetryBlockWriter - Dropped 18 metrics from batch due to invalid metric contents (you should fix this) 
11:37:41.082 [pool-1-thread-1] INFO  c.n.t.m.j.MetricBatchJsonTelemetryBlockWriter - Dropped 18 metrics from batch due to invalid metric contents (you should fix this) 
11:37:46.084 [pool-1-thread-1] INFO  c.n.t.m.j.MetricBatchJsonTelemetryBlockWriter - Dropped 18 metrics from batch due to invalid metric contents (you should fix this) 
11:37:51.084 [pool-1-thread-1] INFO  c.n.t.m.j.MetricBatchJsonTelemetryBlockWriter - Dropped 18 metrics from batch due to invalid metric contents (you should fix this) 
11:37:56.086 [pool-1-thread-1] INFO  c.n.t.m.j.MetricBatchJsonTelemetryBlockWriter - Dropped 18 metrics from batch due to invalid metric contents (you should fix this) 
11:38:01.088 [pool-1-thread-1] INFO  c.n.t.m.j.MetricBatchJsonTelemetryBlockWriter - Dropped 18 metrics from batch due to invalid metric contents (you should fix this) 
11:38:06.084 [pool-1-thread-1] INFO  c.n.t.m.j.MetricBatchJsonTelemetryBlockWriter - Dropped 18 metrics from batch due to invalid metric contents (you should fix this) 
11:38:11.086 [pool-1-thread-1] INFO  c.n.t.m.j.MetricBatchJsonTelemetryBlockWriter - Dropped 18 metrics from batch due to invalid metric contents (you should fix this) 
11:38:16.085 [pool-1-thread-1] INFO  c.n.t.m.j.MetricBatchJsonTelemetryBlockWriter - Dropped 18 metrics from batch due to invalid metric contents (you should fix this) 
```

I'm not really sure how I can fix this. They are just normal metrics that don't have any values yet. Maybe those ones should just be silently dropped w/o the log message?

**Comment by breedx-nr** [comment]
Hi @lightbody (long time no see 😁 ).  Thanks for pointing this out.

If you [take a look in the telemetry sdk](https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/df903a3335d04686ade860ea4fbf87d49bd61ff5/telemetry_core/src/main/java/com/newrelic/telemetry/metrics/json/MetricBatchJsonTelemetryBlockWriter.java#L44) you will see where we generate that message.  After logging that, it does attempt to log all of the invalid metrics so that you can better troubleshoot this.  However, in order to take advantage of that, you'll need to briefly enable audit mode, which is even more verbose.

To enable audit mode, call `enableAuditMode()` on the `NewRelicRegistryConfig` (it would be nice if we had a friendly example of this).

These metrics are dropped if the `isValid()` check fails, and the only way that it fails right now is if the value of the metric is `NaN`, but I think you already discovered that.

Does this only happen for a short time during startup or is this happening throughout your application lifecycle?  Would it be possible for you to pre-filter these metrics before they are batched?

**Comment by lightbody** [comment]
Hi there!

Yeah I dropped a breakpoint on there, check it out. I need to see if it's happening consistently in our staging or prod environments, I'll get back to you on that. But you can see the ones being caught were all NaN.

![image](https://user-images.githubusercontent.com/50803/93819963-4aee5b80-fc11-11ea-81aa-7e04d6930e33.png)

**Comment by breedx-nr** [comment]
Yup, good confirmation, thanks.  Would be great to know what piece of instrumentation is creating those...because they're wholly unhelpful. 🤓

**Comment by lightbody** [comment]
Those metrics are produced by Micronaut when using it's standard Kafka integration. They don't cause problems with our Micronaut->Micrometer->Prometheus integration. Guessing they are just ignored?

**Comment by breedx-nr** [comment]
The micrometer <-> New Relic registry is also ignoring them...but it sounds like the logging is too verbose for your liking.  We definitely intended to log these at `INFO` so that new users wouldn't be surprised when their data wasn't showing up in the platform. 

[There is a little bit of info about NaN value gauges here](https://micrometer.io/docs/concepts#_why_is_my_gauge_reporting_nan_or_disappearing), but if the references are lower than your application then it might not be possible to hold references longer.

Do you have a suggestion or any other idea on what changes we could make to help here?

**Comment by XiXiaPdx** [comment]
Hi @lightbody ! It's been awhile and just checking if you would like further assistance with this issue. It sounds this issue is a combination of how Micrometer's gauges can create NaN and our registry's logging behavior. 

Please let us know how we can help here.

**Comment by skkadium** [comment]
@lightbody @breedx-nr We are also facing the same issue. The integration of Micrometer with Newrelic is causing to log this. I've enabled the auditlogs as per the above discussion and will share my observations soon. 

Just a thought, Is it okay to ignore these logs or do we need to address the issue to understand the root cause and resolve the same.

**Comment by guyhanael** [comment]
@skkadium did this work for you as I do not see any other logs that  explain what is the problematic issue

**Comment by skkadium** [comment]
@guyhanael No luck! Meanwhile I have reverted the changes and implemented the monitoring by enabling the JMX via Dockerfile and setting the NEW_RELIC_KAFKA_METRICS_AS_EVENTS_ENABLED to true to alert the team whenever an event is dropped onto the Kafka Topic

**Comment by kford-newrelic** [comment]
Apologies but we don't have the bandwidth to investigate/fix this. If any intrepid member of the community wants to submit a PR to fix this, it would be welcome!
